// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_transfer.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "data_transfer.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace data_transfer {

namespace {


}  // namespace


void protobuf_AssignDesc_data_5ftransfer_2eproto() {
  protobuf_AddDesc_data_5ftransfer_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "data_transfer.proto");
  GOOGLE_CHECK(file != NULL);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_data_5ftransfer_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_data_5ftransfer_2eproto() {
}

void protobuf_AddDesc_data_5ftransfer_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::common::protobuf_AddDesc_common_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023data_transfer.proto\022\rdata_transfer\032\014co"
    "mmon.proto", 50);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "data_transfer.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_data_5ftransfer_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_data_5ftransfer_2eproto {
  StaticDescriptorInitializer_data_5ftransfer_2eproto() {
    protobuf_AddDesc_data_5ftransfer_2eproto();
  }
} static_descriptor_initializer_data_5ftransfer_2eproto_;

// @@protoc_insertion_point(namespace_scope)

}  // namespace data_transfer

// @@protoc_insertion_point(global_scope)
